name: CI

on:
  push:
    tags: 
      - '*'
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Minify JS and CSS
        uses: nizarmah/auto-minify@master
        with:
          js-engine: uglify-js
      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          scp_source: ./*
          scp_target: /var/www/inr-indice-fragilite
          after_script: |
            cd /var/www/inr-indice-fragilite && composer install
