name: Analyze branch

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup sonar scanner
        uses: warchant/setup-sonar-scanner@v1
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0

      - name: 'Run an analysis of the ${{ github.REF }} branch'
        run: sonar-scanner
          -Dsonar.host.url=${{ secrets.SONAR_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.sources=/home/runner/work/inr-indice-fragilite/inr-indice-fragilite
          -Dsonar.coverage.exclusions=/home/runner/work/inr-indice-fragilite/inr-indice-fragilite/infrastrucuture/cities/data/**,/home/runner/work/inr-indice-fragilite/infrastrucuture/statistics/data/**
          -Dsonar.scm.provider=git
